{% set name = "iniconfig" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67f4b9c50da0dedf52af349e7749a80a9057a5031199791b906c3bb3ae878960

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - iniconfig
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/RonnyPfannschmidt/iniconfig
  summary: 'iniconfig: brain-dead simple config-ini parsing'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
